/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventarioNovoRouteImport } from './routes/inventario.novo'
import { Route as InventarioIdRouteImport } from './routes/inventario.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioNovoRoute = InventarioNovoRouteImport.update({
  id: '/inventario/novo',
  path: '/inventario/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioIdRoute = InventarioIdRouteImport.update({
  id: '/inventario/$id',
  path: '/inventario/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/inventario/$id': typeof InventarioIdRoute
  '/inventario/novo': typeof InventarioNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/inventario/$id': typeof InventarioIdRoute
  '/inventario/novo': typeof InventarioNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/inventario/$id': typeof InventarioIdRoute
  '/inventario/novo': typeof InventarioNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/inventario/$id'
    | '/inventario/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/inventario/$id' | '/inventario/novo'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/inventario/$id'
    | '/inventario/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  InventarioIdRoute: typeof InventarioIdRoute
  InventarioNovoRoute: typeof InventarioNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/novo': {
      id: '/inventario/novo'
      path: '/inventario/novo'
      fullPath: '/inventario/novo'
      preLoaderRoute: typeof InventarioNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario/$id': {
      id: '/inventario/$id'
      path: '/inventario/$id'
      fullPath: '/inventario/$id'
      preLoaderRoute: typeof InventarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  InventarioIdRoute: InventarioIdRoute,
  InventarioNovoRoute: InventarioNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
